apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy-deployment 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy 
  template:
    metadata:
      labels:
        app: autodeploy
    spec:
      containers:
      - name: autodeploy 
        image: streezie/autodeploy3 
        ports:
        - containerPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: autodeploy-service0 
spec:
  type: NodePort
  selector:
    app: autodeploy 
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 9091
    nodePort : 30110
